language: node_js
node_js:
- '6.5'
os:
- osx
script:
- node gulp.js build
deploy:
  provider: s3
  access_key_id:
    secure: h2ymc8A91Hqt31EpAX34Rxi0M654RPwRufIPjTp3DnHcaqh5T+EEYrge368gBgzyb8PXfLJxfkXgCVXOiVzMcA1wmU3HSMH0QLHTTO9/uY8qAxw97xigMMyIJoFhGa/oQRf16fSqCRgLjK8Sne5lbVUf/hRmR80xuj1IatMFGoj0nkc0jF1nnmhVCXxBajnJvCyd7sd7PdkElLUxRJV7fI0K01e1Kj1/xQDg9rEkjZ1fx3CTdDSkyUWHwx3m61rkUOmhTTRdLf7y+H2eaz+tNuBeeV/v7slJiLI+TLIGDuR613c7hY+4jVnpDdKNM0lgFJUQKVUV1n7sB6OgwTQhqjbR8kYYJVtbhdEi0BKYm30wSnURIt2W1xGYUueNUIJPUfd+Y95x+13Tgn/16YtE+cSrZg/TDaR9DKpG3VMY2DEupuxRds2a+lI94zwEohhXYMHKZEM5B8UWqjPyPbe0SknL1xKPB0vwiGL/G5ZIPC5W9u6og7wvb7ZkaKzukfzaizbYikfyFfkL5zNa1aP/IvxFeqtFW3WtXDATs+5D78AlfR4stwJ/vdx/X20jmQAgoQx6KUXh6Z7lA4VJiXUzaAMPy42gHH+r+qZGuzp+neMetj34Cm2/pVnHAgI0fl19Nfei34cid6UAI2Swng+BskhRa1HDKggsUa86AB65P/E=
  secret_access_key:
    secure: SykWIeVeGx6lCgt1I+p5A2iyoVITzIPEqliPZYxZ5o6Lx34Tbnv3EbcyhwPWNxrncUApHX3PpP4Wdzz6l0ZlikwYCNRIUwvSMK4Sk6XuCO3BGDPbfgWDioMmexqtHYJ27c7IVPP1yfJU1PT5euyUrfDTcjWC5ymyIZBxxca8b6+pNXZrg0UbdGmnakGV2Thg7gaIXNxmrSqoY8FEI0k0JFPX1adm5fEfOs4SkX5t8Vj6DqW58eim5b/y9Gajdlj5wvPM4lLWlEaM8OLixUmjy6pa3PUNoSJ4MS+ehgyXRw3GxSo6gQDhDGAxlHCyuQtFBjKxyy6TPfU6RDZsCQxt5dpqUSjzYe903XXME1on3FGOMocSfRWf98+veyf+nexX8PIVGv9sQnaW7qz+sU3yCYNnJbjatDU7nyCgHCViEYxYqmgY2+rKeRZuEeYx3F22AtkH+InuGR0omCwfEBfQFgot9Q2tdvyin7kqmpsxoTYaZCpSgotFOr9QFvKt9Y3Q2qBCYSzweJ6QypbQTCgRqBsa/pKyb7OSxXcWekASiFEpsMOKS8byQoeofabWM/vnbfPpwPsUSuPwjXFXtPpyPS2RPburHuMBdOBlO6tWvXm7W9BFAP3Iw43PtCGPp1Fa1VfQmECyqtrwOuSqMr3ih4LWtwyZj5ur++Jtutq2U7k=
  bucket: quirkbot-downloads-stage
  region: us-east-1
  local_dir: build
  upload-dir: quirkbot-lite-builds
  skip_cleanup: true
